name: roman_numerals_converter
description: A simple Roman numerals converter

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  mocktail: ^0.3.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
flutter:
  uses-material-design: true
